# Generated by Django 4.2.6 on 2023-10-10 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_menuitem_parent_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='url',
        ),
    ]
